// Generated by Selenium IDE
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading;

[TestFixture]
[DisplayName("AuthorizationLogInLogout")] // <- Вот название группы
public class AuthorizationLogInLogoutTestTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    private WebDriverWait wait;

    [SetUp]
    public void SetUp()
    {
        var options = new ChromeOptions();
        options.AddArgument("--start-maximized");
        driver = new ChromeDriver(options);
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
        wait = new WebDriverWait(driver, TimeSpan.FromSeconds(25));
    }

    [TearDown]
    protected void TearDown()
    {
        driver?.Quit();
        driver?.Dispose();
    }

    [Test]
    public void AuthorizationLogInLogoutTest()
    {
        // Step 1: Navigate to login page
        driver.Navigate().GoToUrl("https://ai-ecosystem-test.janusww.com:9999/auth/login.html");

        // Step 2: Wait for and fill login field
        var loginField = wait.Until(d => d.FindElement(By.Id("loginform-login")));
        loginField.Clear();
        loginField.SendKeys("v_shutenko");

        // Step 3: Wait for and fill password field
        var passwordField = wait.Until(d => d.FindElement(By.Id("loginform-password")));
        passwordField.Clear();
        passwordField.SendKeys("8nEThznM");

        // Step 4: Click login button
        wait.Until(d => d.FindElement(By.CssSelector(".icon-circle-right2"))).Click();

        // Step 5: Wait for successful login - check for user dropdown
        wait.Until(d => d.FindElement(By.CssSelector(".dropdown-user")));

        // Small pause for UI stabilization
        Thread.Sleep(1000);

        // Step 6: Click user dropdown
        var userDropdown = wait.Until(d => d.FindElement(By.CssSelector(".dropdown-user .caret")));
        userDropdown.Click();

        // Small pause for menu opening
        Thread.Sleep(500);

        // Step 7: Find and click logout button
        var logoutButton = wait.Until(d => d.FindElement(By.LinkText("Logout")));
        logoutButton.Click();

        // Step 8: Wait for return to login page
        wait.Until(d =>
        {
            var currentUrl = d.Url.ToLower();
            return currentUrl.Contains("login") ||
                   d.FindElements(By.Id("loginform-login")).Count > 0;
        });

        // Step 9: Verify we are on login page
        var loginInputs = wait.Until(d => d.FindElements(By.Id("loginform-login")));
        Assert.That(loginInputs.Count, Is.GreaterThan(0), "Login fields not found after logout");

        // Step 10: Re-enter credentials to verify functionality
        var loginFieldAfterLogout = loginInputs.First();
        loginFieldAfterLogout.Clear();
        loginFieldAfterLogout.SendKeys("v_shutenko");

        var passwordFieldAfterLogout = wait.Until(d => d.FindElement(By.Id("loginform-password")));
        passwordFieldAfterLogout.Clear();
        passwordFieldAfterLogout.SendKeys("8nEThznM");

        // Final verification
        Assert.That(driver.Url.ToLower().Contains("login"), "Failed to confirm logout - not on login page");

        Console.WriteLine("Test completed successfully: Login and logout performed correctly");
    }
}